language: python
sudo: false
python:
  - "2.7"
addons:
  mariadb: '10.2'
env:
  - TZ=Europe/Kiev
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==7.0
  - python2 bootstrap.py
services: mariadb
install:
  - bin/buildout -N
script:
  - bin/nosetests
after_success:
  - bin/coveralls

